#!/usr/bin/python3
import tkinter as tk
import tkinter.ttk as ttk


class MmtWidget(ttk.Notebook):
    def __init__(self, master=None, **kw):
        super(MmtWidget, self).__init__(master, **kw)
        frame1 = ttk.Frame(self)
        frame1.configure(height=200, width=200)
        notebook1 = ttk.Notebook(frame1)
        notebook1.configure(height=200, width=200)
        frame4 = ttk.Frame(notebook1)
        frame4.configure(height=200, width=200)
        frame5 = ttk.Frame(frame4)
        frame5.configure(height=200, width=200)
        label4 = ttk.Label(frame5)
        label4.configure(text='topic')
        label4.pack(padx=5, side="left")
        self.topicsubentry = ttk.Entry(frame5)
        self.topic = tk.StringVar()
        self.topicsubentry.configure(textvariable=self.topic)
        self.topicsubentry.pack(padx=5, side="left")
        self.button1 = ttk.Button(frame5)
        self.button1.configure(text='send', width=4)
        self.button1.pack(side="left")
        self.button1.configure(command=self.publishsigle)
        combobox2 = ttk.Combobox(frame5)
        self.qos = tk.StringVar()
        combobox2.configure(textvariable=self.qos, values='0 1 2', width=1)
        combobox2.pack(pady=0, side="right")
        label5 = ttk.Label(frame5)
        label5.configure(text='QoS')
        label5.pack(padx=2, side="right")
        self.checkbutton1 = ttk.Checkbutton(frame5)
        self.retain = tk.StringVar()
        self.checkbutton1.configure(
            offvalue=0, onvalue=1, variable=self.retain)
        self.checkbutton1.pack(side="right")
        label6 = ttk.Label(frame5)
        label6.configure(text='Retain')
        label6.pack(padx=2, side="right")
        frame5.pack(fill="x", pady=10, side="top")
        panedwindow2 = ttk.Panedwindow(frame4, orient="horizontal")
        panedwindow2.configure(height=200, width=200)
        labelframe3 = ttk.Labelframe(panedwindow2)
        labelframe3.configure(height=200, text='Payload input', width=200)
        self.payloadsub = tk.Text(labelframe3)
        self.payloadsub.configure(height=10, width=50)
        self.payloadsub.pack(expand="true", fill="both", side="top")
        labelframe3.pack(expand="true", fill="both", side="top")
        panedwindow2.add(labelframe3, weight="1")
        labelframe4 = ttk.Labelframe(panedwindow2)
        labelframe4.configure(height=200, text='Payload status', width=200)
        treeview1 = ttk.Treeview(labelframe4)
        treeview1.configure(selectmode="extended")
        treeview1.pack(expand="true", fill="both", side="top")
        labelframe4.pack(side="top")
        panedwindow2.add(labelframe4, weight="1")
        panedwindow2.pack(expand="true", fill="both", side="top")
        frame4.pack(side="top")
        notebook1.add(frame4, text='Sigle')
        frame6 = ttk.Frame(notebook1)
        frame6.configure(height=200, width=200)
        frame8 = ttk.Frame(frame6)
        frame8.configure(height=200, width=200)
        text5 = tk.Text(frame8)
        text5.configure(height=10, state="normal", takefocus=True, width=50)
        _text_ = 'message theo dạng\n{\n   "messsage":[\n      {\n\t"topic":"<topic>", \t\n\t"payload":"<payload"", \n\t"qos":<qos>,\n\t"retain":<retain>\n\t}\n   ]\n}'
        text5.insert("0.0", _text_)
        text5.pack(fill="both", side="top")
        frame8.pack(fill="x", pady=10, side="top")
        panedwindow3 = ttk.Panedwindow(frame6, orient="horizontal")
        panedwindow3.configure(height=200, width=200)
        labelframe5 = ttk.Labelframe(panedwindow3)
        labelframe5.configure(height=200, text='Payload input', width=200)
        text4 = tk.Text(labelframe5)
        text4.configure(height=10, width=50)
        text4.pack(expand="true", fill="both", side="top")
        labelframe5.pack(expand="true", fill="both", side="top")
        panedwindow3.add(labelframe5, weight="1")
        labelframe6 = ttk.Labelframe(panedwindow3)
        labelframe6.configure(height=200, text='Payload status', width=200)
        treeview2 = ttk.Treeview(labelframe6)
        treeview2.configure(selectmode="extended")
        treeview2.pack(expand="true", fill="both", side="top")
        labelframe6.pack(side="top")
        panedwindow3.add(labelframe6, weight="1")
        panedwindow3.pack(expand="true", fill="both", side="top")
        button3 = ttk.Button(frame6)
        button3.configure(text='send')
        button3.pack(side="bottom")
        button3.configure(command=self.publishmulti)
        frame6.pack(side="top")
        notebook1.add(frame6, text='Multi')
        frame7 = ttk.Frame(notebook1)
        frame7.configure(height=200, width=200)
        treeview5 = ttk.Treeview(frame7)
        treeview5.configure(selectmode="extended")
        treeview5.pack(expand="true", fill="both", side="top")
        frame7.pack(expand="true", fill="both", side="top")
        notebook1.add(frame7, text='Message status')
        notebook1.pack(expand="true", fill="both", side="top")
        frame1.pack(side="top")
        self.add(frame1, text='publish')
        self.configure(height=600, width=600)
        self.pack(expand="true", fill="both", side="top")

    def publishsigle(self):
        pass

    def publishmulti(self):
        pass


if __name__ == "__main__":
    root = tk.Tk()
    widget = MmtWidget(root)
    widget.pack(expand=True, fill="both")
    root.mainloop()
